#!/bin/bash
# Mechanical audit of DriftCore's public API surface.
#
# For every public/open type declaration in DriftCore/Sources/, count usages
# outside DriftCore/Sources/ (the rest of the repo). Symbols with zero
# external references are candidates for `internal` downgrade.
#
# Output:
#   /tmp/public-api-audit.tsv   — sortable, one symbol per line
#   /tmp/public-api-audit.md    — readable report grouped by external_ref count
#
# Notes / known limits:
#   - Counts type-level declarations (class/struct/enum/protocol/actor/typealias).
#     Member-level trimming (public var, public init on a kept type) is a
#     separate follow-up.
#   - "External" = anywhere in the repo OUTSIDE DriftCore/Sources/. That
#     includes Drift/, DriftTests/, DriftCore/Tests/, DriftLLMEvalMacOS/,
#     DriftWidget/ (if it exists), DriftIntents/ (if it exists). Tests using
#     @testable import DriftCore reach internal members anyway, so a symbol
#     used only in a test file is still a downgrade candidate.
#   - We grep for the bare type name. False positives possible if the name
#     is a common English word (e.g. "Workout"). Eyeball the report.
set -uo pipefail
# Don't `set -e`: grep returns 1 on no-match, and we have many empty-result greps.

cd "$(git rev-parse --show-toplevel)"

SRC=DriftCore/Sources/DriftCore
EXTERNAL_PATHS=(Drift DriftTests DriftCore/Tests DriftLLMEvalMacOS DriftWidget DriftIntents DriftLLMEvalTests)

# Collect every public/open type-level declaration.
# Match patterns:
#   public class Foo, public struct Foo, public enum Foo, public protocol Foo,
#   public actor Foo, public final class Foo, public typealias Foo
# We deliberately skip `public extension X` — extensions don't add a new
# symbol, they extend an existing one; the extended type drives visibility.

> /tmp/public-api-audit.tsv
echo -e "symbol\tkind\tfile:line\texternal_refs\tcandidate" >> /tmp/public-api-audit.tsv

# Find type declarations
grep -rEn "^(public|open) (final |indirect )*(class|struct|enum|protocol|actor|typealias) " "$SRC" --include="*.swift" \
  | while IFS=: read -r file line content; do
    # Extract symbol name: strip access keyword, modifiers, kind keyword, get next identifier
    sym=$(echo "$content" | perl -ne '
      if (/^\s*(public|open)\s+(final\s+|indirect\s+)*(class|struct|enum|protocol|actor|typealias)\s+([A-Za-z_][A-Za-z0-9_]*)/) {
          print "$3\t$4";
      }')
    [ -z "$sym" ] && continue
    kind=$(echo "$sym" | cut -f1)
    name=$(echo "$sym" | cut -f2)

    # Count external refs: grep the bare identifier outside DriftCore/Sources/.
    # Use \b word boundary so "Food" doesn't match "FoodEntry".
    count=0
    for ext in "${EXTERNAL_PATHS[@]}"; do
        [ -d "$ext" ] || continue
        n=$(grep -rEw "$name" "$ext" --include="*.swift" 2>/dev/null | wc -l | tr -d ' ' || true)
        count=$((count + n))
    done

    # Verdict
    if [ "$count" -eq 0 ]; then
        verdict="DOWNGRADE_CANDIDATE"
    elif [ "$count" -le 2 ]; then
        verdict="LOW_USE_REVIEW"
    else
        verdict="KEEP"
    fi

    echo -e "${name}\t${kind}\t${file}:${line}\t${count}\t${verdict}" >> /tmp/public-api-audit.tsv
done

# Also catch top-level public funcs and global vars (rare but exist).
grep -rEn "^(public|open) (func|var|let) " "$SRC" --include="*.swift" \
  | while IFS=: read -r file line content; do
    sym=$(echo "$content" | perl -ne '
      if (/^\s*(public|open)\s+(func|var|let)\s+([A-Za-z_][A-Za-z0-9_]*)/) {
          print "$2\t$3";
      }')
    [ -z "$sym" ] && continue
    kind=$(echo "$sym" | cut -f1)
    name=$(echo "$sym" | cut -f2)

    count=0
    for ext in "${EXTERNAL_PATHS[@]}"; do
        [ -d "$ext" ] || continue
        n=$(grep -rEw "$name" "$ext" --include="*.swift" 2>/dev/null | wc -l | tr -d ' ' || true)
        count=$((count + n))
    done

    if [ "$count" -eq 0 ]; then verdict="DOWNGRADE_CANDIDATE"
    elif [ "$count" -le 2 ]; then verdict="LOW_USE_REVIEW"
    else verdict="KEEP"
    fi

    echo -e "${name}\t${kind}\t${file}:${line}\t${count}\t${verdict}" >> /tmp/public-api-audit.tsv
done

# Build the markdown report
{
echo "# DriftCore Public API Audit — $(date +%Y-%m-%d)"
echo ""
echo "Auto-generated by \`scripts/public-api-audit.sh\`. Counts type-level + top-level public/open declarations and tallies external references in the rest of the repo."
echo ""
total=$(tail -n +2 /tmp/public-api-audit.tsv | wc -l | tr -d ' ')
downgrade=$(awk -F'\t' '$5 == "DOWNGRADE_CANDIDATE"' /tmp/public-api-audit.tsv | wc -l | tr -d ' ')
lowuse=$(awk -F'\t' '$5 == "LOW_USE_REVIEW"' /tmp/public-api-audit.tsv | wc -l | tr -d ' ')
keep=$(awk -F'\t' '$5 == "KEEP"' /tmp/public-api-audit.tsv | wc -l | tr -d ' ')
echo "## Summary"
echo ""
echo "| Verdict | Count |"
echo "|---|---|"
echo "| Total declarations | $total |"
echo "| **DOWNGRADE_CANDIDATE** (0 external refs) | $downgrade |"
echo "| **LOW_USE_REVIEW** (1-2 external refs) | $lowuse |"
echo "| KEEP (3+ external refs) | $keep |"
echo ""
echo "## DOWNGRADE_CANDIDATE — zero external refs"
echo ""
echo "These are declared \`public\` but referenced only inside \`DriftCore/Sources/\`. Strong candidates for \`internal\` downgrade. Verify each before downgrading — false positives possible if the symbol name shadows an English word."
echo ""
echo "| Symbol | Kind | Location |"
echo "|---|---|---|"
awk -F'\t' '$5 == "DOWNGRADE_CANDIDATE" { printf "| `%s` | %s | `%s` |\n", $1, $2, $3 }' /tmp/public-api-audit.tsv | sort
echo ""
echo "## LOW_USE_REVIEW — 1-2 external refs"
echo ""
echo "Used externally, but barely. Worth eyeballing — the use site might be incidental (e.g. a single test) and the symbol could still go internal."
echo ""
echo "| Symbol | Kind | Location | External refs |"
echo "|---|---|---|---|"
awk -F'\t' '$5 == "LOW_USE_REVIEW" { printf "| `%s` | %s | `%s` | %d |\n", $1, $2, $3, $4 }' /tmp/public-api-audit.tsv | sort
} > /tmp/public-api-audit.md

# Print summary to stdout
echo ""
echo "Total public type-level + top-level declarations: $total"
echo "  DOWNGRADE_CANDIDATE: $downgrade"
echo "  LOW_USE_REVIEW:      $lowuse"
echo "  KEEP:                $keep"
echo ""
echo "Reports:"
echo "  /tmp/public-api-audit.tsv  (sortable raw)"
echo "  /tmp/public-api-audit.md   (readable report)"
